### ISSUE TITLE
update parser to be compatible with standard-version

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/changelog-parser#14]
https://github.com/conventional-changelog/standard-version produces change logs with versions that have different heading sizes. This breaks the parser. In a perfect world they wouldn't do that, but for now the parser should not fail if headings are not consistent.

**Comment by ungoldman** [comment]
See also: https://github.com/conventional-changelog/standard-version/issues/208

**Comment by ungoldman** [comment]
Don't really want to fork standard-version, but I might just to make a changelog template that conforms to http://keepachangelog.com and works with other changelog parsers.

**Comment by bcoe** [comment]
@marcysutton @ungoldman would love your help getting the default template used by standard-version to generate valid HTML; and will happily help land any pull requests you submit.

If you feel like prodding me in chat, I put together a community slack for [yargs, Istanbul, and conventional-changelog](devtoolscommunity.herokuapp.com).

**Comment by ungoldman** [comment]
Thanks @bcoe! I will try to open a PR soon if @marcysutton doesn't get there first :)

Note: Edited your above comment just to fix the link (missing `https://`).
