### ISSUE TITLE
Add Promise support

### ISSUE THREAD

**Issue by jrmykolyn** [hypermodules/changelog-parser#18]
Currently, `parseChangelog()` expects a callback argument, which allows the user to access the parsed changelog data with the body of the function. Eg.

```
// Callback functionality
parseChangelog( 'path/to/file', function( err, result ) {
    if ( err ) return;

    console.log( result );
} );
```

Proposed update would supplement the current functionality/behavior by returning a Promise in cases where `parseChangelog` *is not* invoked with a callback. Eg.

```
// Promise functionality
parseChangelog( 'path/to/file' )
    .then( function( result ) {
        console.log( result )
    } )
    .catch( function() {
        // Whoops, something went wrong!
    } );
```

This update would allow `parseChangelog()` to be easily inserted into 'Promise chain' procedures. Eg.

```
let result = getPath( 'CHANGELOG.md' )
                .then( parseChangelog )
                .then( getVersions );
```

**Comment by jrmykolyn** [comment]
@ungoldman 

Submitted PR #19 against this. Let me know if this feature sounds worthwhile, and/or if there's any updates you'd like to see?

**Comment by ungoldman** [comment]
Thanks again @jrmykolyn! I've invited you to be a collaborator on this project as you've made some significant improvements. Feel free to continue improving it as you see fit, just be sure to read the [guidelines](https://github.com/hypermodules/changelog-parser/blob/master/CONTRIBUTING.md#collaborating-guidelines) for collaborators. The important rules are as follows:

> 1. **No `--force` pushes** or modifying the Git history in any way.
> 1. **Non-master branches** ought to be used for ongoing work.
> 1. **External API changes and significant modifications** ought to be subject to an **internal pull-request** to solicit feedback from other contributors.
> 1. Internal pull-requests to solicit feedback are *encouraged* for any other non-trivial contribution but left to the discretion of the contributor.
> 1. Contributors should attempt to adhere to the prevailing code style.

**Comment by jrmykolyn** [comment]
@ungoldman Awesome! Thanks for inviting me!
