### ISSUE TITLE
Add parsed/sorted data to changelog entry objects

### ISSUE THREAD

**Issue by jrmykolyn** [hypermodules/changelog-parser#20]
Currently, all markdown/data for a given entry is provided via the `body` key on the changelog object. This is perfect for many use cases, but I've bumped into a situation where I need access to the individual items of a specific type from a particular entry (eg. everything 'Added' as part of '1.0.0'). To achieve this, I'm parsing the markdown (provided via `body`) into a series of plain text arrays. 

If possible, I would love to have this information made available 'out of the box' for each entry.

For example, the following entry...

```
## [1.0.0] - 2018-01-04
### Added
- Added `gh-release` to development dependencies.

### Changed
- Updated dependency version.
- Fixed broken tests.
```

...would be parsed to:

```
{
    version: '1.0.0',
    title: '[1.0.0] - 2018-01-04',
    date: '2018-01-04',
    body: '## [1.0.0] - 2018-01-04 ...',
    bodyParsed: {
        added: [
            'Added `gh-release` to development dependencies.',
        ],
        changed: [
            'Updated dependency version.',
            'Fixed broken tests.',
        ],
    },
}
```

If you approve, I'm happy to take a crack at building out/testing this functionality?

**Comment by jrmykolyn** [comment]
@ungoldman Side note: How can I become part of the 'hypermodules' organization?

**Comment by ungoldman** [comment]
@jrmykolyn saw this earlier today, but it's been a busy one! I'll get back to you soon. Assigned myself to the issue so I don't forget.

**Comment by jrmykolyn** [comment]
@ungoldman 🙏

**Comment by jrmykolyn** [comment]
@ungoldman

Submitted PR #21 against this. Let me know what you think.

**Comment by ungoldman** [comment]
@jrmykolyn Your proposal looks fine to me. Reviewed your PR.

As for becoming a member of the hypermodules org, all you have to do is ask :)

This org is mainly a home for projects @bcomnes and I have created that benefit from shared maintainership, though I guess it may be growing into something more.

I have three questions for you:

Why do you want to join the org?
Have you had a chance to read the FAQ on https://hypermodul.es?
Do you swear allegiance to our Dark Lord Cthulhu for all eternity?

**Comment by jrmykolyn** [comment]
@ungoldman 

Cool, thanks for getting back to me RE: PR.

In terms of joining the `hypermodules` org, I have three responses:
1. I'm part of a few teams IRL, but one of my resolutions this year is to contribute more to the open source tools that I use in my personal and professional work.
2. Just a quick a skim. I'll take a deeper dive tonight.
3.Yes (but I think Yig: Father of Serpents wins 'best name').

**Comment by bcomnes** [comment]
We can add you as contributor on any repo you are working on, or add you to the org if you want the  firehose of potentially unrelated repos, but you have to join irc :p

**Comment by jrmykolyn** [comment]
@bcomnes Hey hey. Happy to join the org. and poke around under the hood. If you think it doesn
't make sense, I'm having a great time working on `changelog-parser` and `gh-releases`.

**Comment by ungoldman** [comment]
@jrmykolyn sent you an invite 🖖
