### ISSUE TITLE
Hi. I made changelog-parser-action

### ISSUE THREAD

**Issue by ocavue** [hypermodules/changelog-parser#36]
First of all, great project. 👍

I made https://github.com/ocavue/changelog-parser-action on the top of this project. Users can use changelog-parser-action to parse CHANGELOG in their GitHub Action workflows and combine it with other Actions together. 

Any feedback and suggestions will be appreciated.

**Comment by ungoldman** [comment]
Looks great! No feedback other than to say thank you and good luck! This module is not _super_ actively maintained (despite ~55k downloads per month 😂), I'm glad it's still working.

**Comment by ungoldman** [comment]
Going to close this as it's not an issue :)
