### ISSUE TITLE
use mdast to parse markdown?

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/changelog-parser#5]
IS IT WORTH IT?

https://github.com/wooorm/mdast

**Comment by ngoldman** [comment]
pong @bcomnes @paulcpederson @kneemer 

this module is used by gh-release

using mdast would allow us to do more fancy things down the road (validating, adding compare links, generating things)

**Comment by wooorm** [comment]
Yes, mdast is worth it! 😛

**Comment by bcomnes** [comment]
Yeah LGTM.

**Comment by ungoldman** [comment]
Nobody's available or motivated to do this right now, so I'm closing! 👋
