### ISSUE TITLE
Extract date into seperate key

### ISSUE THREAD

**Issue by Hirse** [hypermodules/changelog-parser#6]
Parallel to the version it would be nice to have the date extracted into its own key in the version object.

**Comment by ungoldman** [comment]
Agreed, that would be nice! But change logs don't always include that information. How would you suggest handling missing values? `null`?

**Comment by Hirse** [comment]
Seems reasonable, especially since that is how a missing version is handled.

**Comment by ungoldman** [comment]
@Hirse PR welcome! I'll try to get to this soon if you don't first.

**Comment by jrmykolyn** [comment]
:wave:

Hello! Still accepting PRs against this issue?

**Comment by ungoldman** [comment]
Yes! Thanks for tackling this issue @jrmykolyn!

**Comment by ungoldman** [comment]
@jrmykolyn your PR has been merged and released in [`v2.1.0`](https://github.com/hypermodules/changelog-parser/releases/tag/v2.1.0).

**Comment by jrmykolyn** [comment]
@ungoldman 

My pleasure, thanks for merging/releasing so quickly!
